-keep class com.jon2g.onetaphabits.AppWidgets.** { *; }
-keep class OneTapHabits.Platforms.Android.AppWidgets.** { *; }
-keep class OneTapHabits.MainActivity { *; }
-keep class OneTapHabits.Services.UpdateService { *; }
-keep class OneTapHabits.Services.UpdateCoordinator { *; }
-keep class OneTapHabits.Views.UpdatePopupPage { *; }
-keep class com.google.firebase.** { *; }
-keep class com.google.android.gms.** { *; }
-dontwarn com.google.android.gms.**
