//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneTapHabits.Resources.Strings;

using System.Globalization;
using System.Resources;

public class AppResources
{
	private static readonly ResourceManager ResourceManager =
		new("OneTapHabits.Resources.Strings.AppResources", typeof(AppResources).Assembly);

	public static string Get(string name) =>
		ResourceManager.GetString(name, CultureInfo.CurrentUICulture) ?? name;
}
